language: cpp

branches:
  only:
    - master
    - develop
    - feature-travis

compiler: 
  - gcc
  - clang

os:
- linux
- osx
  
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential
  
install:
  - sudo apt-get install git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev checkinstall
  - sudo apt-get install libboost1.55-all-dev
  
before_script:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - cd ../..

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE ..
  - make
  - ./bin/FaceLandmarkImg -fdir "../videos/" -ofdir "./demo_img/" -oidir "./demo_img/" -wild -q