language: cpp

branches:
  only:
    - master
    - develop
    - /^feature-.*$/
compiler:
  - gcc

os:
  - osx
  - linux  
  
before_install:

  # OpenCV dependencies and boost
  - if [ ${TRAVIS_OS_NAME} = linux ]; then  
      apt-get install git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev;      
      apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev checkinstall;
      apt-get install cmake;
      apt-get update;
      apt-get install libboost1.55-all-dev;
      wget https://github.com/Itseez/opencv/archive/3.1.0.zip;
      unzip 3.1.0.zip;
      opencv-3.1.0;
      mkdir build;
      build;
    fi

  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then
      if [ ${TRAVIS_OS_NAME} = linux ]; then
        $CXX --version;
        cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_V4L=ON -D WITH_OPENCL=OFF -D INSTALL_C_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF ..;
      fi 
    fi

  # clang 3.4
  - if [ "$CXX" = "clang++" ]; then
      if [ ${TRAVIS_OS_NAME} = linux ]; then  
        $CXX --version;
        cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_V4L=ON -D WITH_OPENCL=OFF -D INSTALL_C_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D WITH_TBB=ON ..;
      fi
    fi

  - if [ ${TRAVIS_OS_NAME} = osx ]; then
      brew update;
      brew install tbb;
      brew install opencv3 --HEAD
    fi

before_script:
  - make -j4
  - make install
  - cd ../.. 
  
script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE CMAKE_CXX_FLAGS="-std=c++11" -D CMAKE_EXE_LINKER_FLAGS="-std=c++11" .. 
  - make -j2
  - ../build/bin/FaceLandmarkImg -fdir "../samples/" -out_dir "./demo_img/"  -wild -q
  - ../build/bin/FaceLandmarkImg -inroot ../samples -f sample1.jpg -out_dir data -of sample1.txt -multi_view 1 -wild -q
  - ../build/bin/FaceLandmarkVidMulti -inroot ../samples -f multi_face.avi -q
  - ../build/bin/FeatureExtraction -f "../samples/2015-10-15-15-14.avi" -out_dir -q
  - ../build/bin/FeatureExtraction -f "../samples/2015-10-15-15-14.avi"  -simsize 200 -simscale 0.5 -q
  - ../build/bin/FaceLandmarkVid -inroot ../samples -f 2015-10-15-15-14.avi -f multi_face.avi -q
